# Generated by Django 5.2.3 on 2025-06-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('statement', models.TextField()),
                ('difficulty', models.CharField(max_length=20)),
                ('time_limit', models.FloatField()),
                ('memory_limit', models.IntegerField()),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
    ]
