# Generated by Django 5.2.3 on 2025-06-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='extra_testcases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
