# Generated by Django 5.2.3 on 2025-06-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_extra_testcases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='extra_testcases',
        ),
        migrations.AddField(
            model_name='problem',
            name='hidden_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='hidden_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
