# Generated by Django 5.2.3 on 2025-06-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_remove_problem_extra_testcases_problem_hidden_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='hidden_input',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='hidden_output',
        ),
        migrations.AddField(
            model_name='problem',
            name='test_cases',
            field=models.JSONField(default=list),
        ),
    ]
