# Generated by Django 5.2.3 on 2025-06-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submission_options_alter_submission_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
